runtime: python310

entrypoint: gunicorn -b :$PORT run:app

handlers:
- url: /static
  static_dir: app/static

- url: /.*
  script: auto

env_variables:
  FLASK_APP: run.py
  FLASK_ENV: production

runtime_config:
  python_version: 3.10

requirements_txt: requirements.txt